### PR TITLE
WIP: Add GitHub action to build multi-arch docker images

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by JohnNiang** [comment]
> /hold
> 
> This CI building is failed. See also https://github.com/LinuxSuRen/s2i-python-container/runs/2774691708?check_suite_focus=true
> 
> I will un-hold it if it works well.

Alright. I'm sorry for that.

**Comment by LinuxSuRen** [comment]
I guess some packages do not have the arm64 arch. Three of the image building works well. See also https://github.com/LinuxSuRen/s2i-python-container/runs/2775104398?check_suite_focus=true

**Pull request merged**
